syntax on

" Indentation
filetype plugin indent on
set expandtab
set tabstop=4
set softtabstop=4
set autoindent
set shiftwidth=4

" Line numbers
set number
set numberwidth=4

" Backup and swap files
set nobackup
set nowritebackup
set noswapfile

" Escape from Insert mode
inoremap jk <ESC>

" Aid to setup `lightline` plugin
set laststatus=2

" Plugins with vim-plug
call plug#begin('~/.vim/plugged')

Plug 'ervandew/supertab'
Plug 'itchyny/lightline.vim'

call plug#end()
