" General
syntax on
set showcmd
set encoding=utf-8
set shell=/bin/bash

" Indentation
filetype plugin indent on
set expandtab
set tabstop=4
set softtabstop=4
set autoindent
set shiftwidth=4

" Line numbers
set number
set numberwidth=4

" Backup and swap files
set nobackup
set nowritebackup
set noswapfile

" Mappings
let mapleader = " "
inoremap jk <ESC>
nnoremap <Leader>w <C-w>

" Aid to setup `lightline` plugin
set laststatus=2

" Plugins with vim-plug
call plug#begin('~/.vim/plugged')
Plug 'ervandew/supertab'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'terryma/vim-multiple-cursors'
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'sheerun/vim-polyglot'
Plug 'w0rp/ale'
Plug 'python-rope/ropevim'
call plug#end()

" Configure plugins
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1

nnoremap <silent> <Leader>t :NERDTreeToggle<CR>

colorscheme seoul256

nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>fr :Rg<CR>
nnoremap <Leader>fb :Buffers<CR>
nnoremap <Leader>fl :Lines<CR>
nnoremap <Leader>fw :BLines<CR>
nnoremap <Leader>fc :History:<CR>

let ropevim_local_prefix = '<Leader>r'
let ropevim_global_prefir = '<Leader>p'

let g:ale_linters = {
\    'python': ['flake8', 'pyls']
\}

nmap <silent> <Leader>ag <Plug>(ale_go_to_definition)
nmap <silent> <Leader>au <Plug>(ale_find_references)
