" General
syntax on
set encoding=utf-8
set shell=/bin/bash

" Indentation
filetype plugin indent on
set expandtab
set tabstop=4
set softtabstop=4
set autoindent
set shiftwidth=4

" Editor
set showcmd
set hidden
set wildmenu
set number
set numberwidth=4
set colorcolumn=80

" Backup and swap files
set nobackup
set nowritebackup
set noswapfile

" Mouse support
set mouse=a

if !has('nvim')
  set ttymouse=xterm2 " for mouse to work under tmux
endif

" Mappings
let mapleader = " "
inoremap jk <ESC>

nmap <Leader>w <C-w>
" Maximaze current buffer
nnoremap <C-W>z :NERDTreeClose<CR><C-W>\|<C-W>_

" Show file path for the current buffer
nnoremap <Leader>lp 1<C-g>

nmap <Leader>lb oimport ipdb; ipdb.set_trace()<ESC>

" Highlight instances of token under the cursor
nmap <silent> <Leader>lh :call personal#Highlight()<CR>
nmap <silent> <Leader>lu :call personal#Unhighlight()<CR>

" Replace visually selected region
vmap <silent> <Leader>lr :call personal#Replace()<CR>

nmap <Leader>ls :call personal#CppSwitch()<CR>
nmap <Leader>ln :call personal#NameNoName()<CR>

" Aid to setup `lightline` plugin
set laststatus=2

" Plugins with vim-plug
call plug#begin('~/.vim/plugged')
Plug 'ervandew/supertab'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'sheerun/vim-polyglot'
Plug 'w0rp/ale'
Plug 'python-rope/ropevim'
Plug '907th/vim-auto-save'
call plug#end()

" Configure plugins
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1

nnoremap <silent> <Leader>tt :NERDTreeToggle<CR>
nnoremap <silent> <Leader>to :NERDTree<CR><C-w>p
nnoremap <silent> <Leader>tf :NERDTreeFind<CR>

colorscheme seoul256

" Ignore filenames in files search
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>),
  \   1, fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}),
  \   <bang>0)

nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>fr :Rg<CR>
nnoremap <Leader>fb :Buffers<CR>
nnoremap <Leader>fl :Lines<CR>
nnoremap <Leader>fw :BLines<CR>
nnoremap <Leader>fc :History:<CR>

let ropevim_local_prefix = '<Leader>r'
let ropevim_global_prefir = '<Leader>p'

let g:ale_linters = {
\    'python': ['flake8', 'jedils']
\}
let g:ale_fixers = {
\    '*': ['remove_trailing_lines', 'trim_whitespace']
\}

nmap <silent> <Leader>a<Space> <Plug>(ale_toggle)
nmap <silent> <Leader>af <Plug>(ale_fix)
nmap <silent> <Leader>ag <Plug>(ale_go_to_definition)
nmap <silent> <Leader>au <Plug>(ale_find_references)
nmap <silent> <Leader>ap <Plug>(ale_previous_wrap)
nmap <silent> <Leader>an <Plug>(ale_next_wrap)

let g:auto_save = 1
let g:auto_save_silent = 1
