#!/bin/sh

server_test=$(tmux ls 2>&1 | grep 'error connecting\|no server running')

if [ -n "$server_test" ]; then
    echo "starting new tmux session..."
else
    echo "error: tmux session found"
    exit 1
fi

tmux set-option -g status-position top

tmux new-session -s work -d

# Maintain window
tmux rename-window -t work maintain
tmux send-keys -t work 'sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
tmux split-window -t work
tmux send-keys -t work '~/bin/fix-dns'
tmux split-window -h -t work -c ~/data/jupyter 'jupyter notebook --no-browser'
tmux select-pane -t work -U
tmux split-window -t work -h
tmux send-keys -t work "snap info firefox | grep 'latest/stable\|installed.*MB' | cat" C-m
tmux split-window -t work -c ~/data/snap
tmux send-keys -t work 'echo snap download firefox' C-m

# First working window
tmux new-window -t work
tmux rename-window -t work first
tmux split-window -h -t work

tmux attach -t work
